# Generated by Django 3.1.1 on 2020-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20200912_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='decription',
            field=models.CharField(max_length=1000),
        ),
    ]
