# Generated by Django 3.1.1 on 2020-09-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20200912_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
