# Generated by Django 3.1.1 on 2020-09-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_auto_20200912_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Book',
        ),
    ]
