# Generated by Django 3.1.1 on 2020-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_auto_20200913_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
