# Generated by Django 3.1.1 on 2020-09-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_auto_20200918_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
