# Generated by Django 3.1.1 on 2020-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0009_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
